name: Simple CI/CD for Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # or windows-latest if you're using Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Oracle JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'  # You can use 'adoptopenjdk' or 'zulu' too

      - name: Build and test with Maven
        run: mvn clean install -DskipTests=false

      - name: Archive JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar

      - name: Print success message
        run: echo "Build and tests completed successfully!"
